# Generated by Django 3.2.8 on 2021-10-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211018_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cummulative_gpa',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_gpa',
            field=models.FloatField(),
        ),
    ]
