# Generated by Django 3.2.8 on 2021-10-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211019_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='eligible',
            field=models.BooleanField(blank=True),
        ),
    ]
